import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { HeaderNavComponent } from "@/components/header-nav";
import StoreProvider from "./StoreProvider";
import AuthAwareComponent from "@/components/auth-aware";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <HeaderNavComponent />
          <AuthAwareComponent>{children}</AuthAwareComponent>
        </body>
      </html>
    </StoreProvider>
  );
}
